# Generated by Django 5.2.7 on 2025-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('email', models.CharField(default='Unknown', max_length=100)),
                ('username', models.CharField(default='Unknown', max_length=100)),
                ('password', models.CharField(default='unknown', max_length=100)),
                ('gender', models.CharField(default='Unknown', max_length=100)),
                ('phone', models.CharField(default='unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(default='Unknown', max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
