# Generated by Django 5.2.7 on 2025-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bauxite', models.FloatField(default='0', max_length=50)),
                ('alumina', models.FloatField(default='0', max_length=50)),
                ('moisture', models.FloatField(default='0', max_length=50)),
                ('soda', models.FloatField(default='0', max_length=50)),
                ('temperature', models.FloatField(default='0', max_length=50)),
                ('residue', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
