# Generated by Django 5.2.7 on 2025-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scrap', '0003_item_approved_item_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
