# Generated by Django 5.2.7 on 2025-11-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_scrap', '0004_alter_item_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Scrap',
        ),
    ]
