# Generated by Django 5.2.7 on 2025-11-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scrap', '0005_rename_item_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
