# Generated by Django 5.2.7 on 2025-11-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scrap', '0006_alter_scrap_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='role',
            field=models.CharField(default='scrapmanagement', max_length=50),
        ),
    ]
