# Generated by Django 5.2.7 on 2025-11-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_scrap", "0007_alter_scrap_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Material",
        ),
    ]
