# Generated by Django 5.2.7 on 2025-10-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rlagent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
