# Generated by Django 5.2.7 on 2025-10-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rlagent', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alumina',
            field=models.FloatField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='bauxite',
            field=models.FloatField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='moisture',
            field=models.FloatField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='soda',
            field=models.FloatField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='temperature',
            field=models.FloatField(default='0', max_length=50),
        ),
    ]
