# Generated by Django 5.2.7 on 2025-10-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rlagent', '0004_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='residue',
            field=models.FloatField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Residue',
        ),
    ]
