# Generated by Django 5.2.7 on 2025-10-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rlagent', '0005_material_residue_material_status_delete_residue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='residue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
