# Generated by Django 5.2.7 on 2025-11-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rlagent', '0006_alter_material_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='role',
            field=models.CharField(default='agent', max_length=50),
        ),
    ]
