# Generated by Django 5.2.7 on 2025-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rlagent', '0008_alter_item_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
