# Generated by Django 5.2.7 on 2025-11-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_deligator', '0005_alter_item_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Deligator',
        ),
    ]
