# Generated by Django 5.2.7 on 2025-11-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_deligator", "0006_rename_item_deligator"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Material",
        ),
    ]
